#@data/values-schema
---

#! Base domain name for all public endpoints
#@schema/validation min_len=1
domain: ""

#! Pod replica counts
replicas:
  ctfd: 1

#! CTFd-specific configuration
ctfd:
  #! Number of vCPUs per CTFd instance (worker count is auto-derived from this value)
  vcpus: 2
  #! Amount of RAM (in MiB) to dedicate per vCPU
  memory: 384

#! Pre-allocated Public IPs
pips:
  #@schema/validation min_len=1
  ingress: ""
  #@schema/validation min_len=1
  challenges: ""
