#@data/values-schema
---

#! Base domain name for all public endpoints
#@schema/validation min_len=1
domain: ""

#! Base domain name for all protected (internal) endpoints
#@schema/validation min_len=1
internal_domain: ""

#! Pod replica counts
replicas:
  ctfd: 1

#! CTFd-specific configuration
ctfd:
  #! Number of vCPUs per CTFd instance
  vcpus: 1
  #! Amount of RAM (in MiB) to dedicate per vCPU
  memory: 384

#! Pre-allocated Public IPs
pips:
  #@schema/validation min_len=1
  ingress: ""
  #@schema/validation min_len=1
  challenges: ""
