#@ load("@ytt:data", "data")

#@ domain = data.values.domain

#@ namespace = "image-registry"
#@ name = "registry"
#@ category = "registry"

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ namespace
  name: #@ name + "-headless"
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  clusterIP: None
  selector:
    app: #@ name
  ports:
  - port: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  replicas: 1
  serviceName: #@ name + "-headless"
  selector:
    matchLabels:
      app: #@ name
  template:
    metadata:
      labels:
        app: #@ name
    spec:
      containers:
      - name: #@ name
        image: "docker.io/library/registry:2"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: "registry-data"
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: "registry-data"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: managed-csi
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  type: ClusterIP
  selector:
    app: #@ name
  ports:
  - port: 5000
---
#! TODO: actually add authorization to restrict access to container images
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  rules:
  - host: #@ "registry." + domain
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
