#@ namespace = "ctfd"
#@ name = "mariadb"
#@ category = "ctfd"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  replicas: 1
  serviceName: #@ name
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name
      app.kubernetes.io/part-of: #@ category
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name
        app.kubernetes.io/part-of: #@ category
    spec:
      containers:
      - name: #@ name
        #! TODO: switch to a non-Ubuntu-based image?
        image: "docker.io/library/mariadb:10.9"
        env:
          - name: MARIADB_RANDOM_ROOT_PASSWORD
            value: "1"
          - name: MARIADB_DATABASE
            value: "ctfd"
          - name: MARIADB_USER
            value: "ctfd"
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ctfd-secrets
                key: database-password
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: managed-csi
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: #@ name
  ports:
  - port: 3306
