#@ namespace = "ctfd"
#@ name = "redis"
#@ category = "ctfd"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name
      app.kubernetes.io/part-of: #@ category
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name
        app.kubernetes.io/part-of: #@ category
    spec:
      containers:
      - name: #@ name
        image: "docker.io/library/redis:7-alpine"
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: #@ name
  ports:
  - port: 6379
