#@ load("@ytt:data", "data")

#@ domain = data.values.domain
#@ internal_domain = data.values.internal_domain

#@ namespace = "auth"
#@ name = "oauth2-proxy"
#@ category = "oauth2-proxy"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name
      app.kubernetes.io/part-of: #@ name
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name
        app.kubernetes.io/part-of: #@ name
    spec:
      containers:
      - name: #@ name
        image: "quay.io/oauth2-proxy/oauth2-proxy:latest"
        args:
        - --http-address=0.0.0.0:4180
        - --provider=github
        - --email-domain=*
        - --github-org=club-eh
        - --github-team=ctf-2023-infrastructure
        - --upstream=file:///dev/null
        #! These domains are allowed to use OAuth2 Proxy
        - #@ "--whitelist-domain=" + internal_domain
        - #@ "--whitelist-domain=*." + internal_domain
        #! Set the cookie on the internal domain, *including subdomains*
        - #@ "--cookie-domain=" + internal_domain
        #! Workaround for https://github.com/oauth2-proxy/oauth2-proxy/issues/1724
        - --scope=user:email
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-client
                key: client-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-client
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secrets
                key: cookie-signing-key
        resources:
          limits:
            cpu: "100m"
            memory: "96Mi"
        ports:
        - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: #@ name
  ports:
  - name: http
    port: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
    app.kubernetes.io/part-of: #@ category
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: #@ internal_domain
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: #@ name
            port:
              name: http
