#@ load("@ytt:data", "data")

#@ internal_domain = data.values.internal_domain

#@ namespace = "monitoring"
#@ name = "grafana-ingress"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: #@ namespace
  name: #@ name
  labels:
    app.kubernetes.io/name: #@ name
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #! Require authorization to access the service
    nginx.ingress.kubernetes.io/auth-signin: #@ "https://" + internal_domain + "/oauth2/start"
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.auth.svc.cluster.local:4180/oauth2/auth
spec:
  tls:
  - secretName: le-admin-ctf-2023-keypair
  rules:
  - host: #@ "grafana." + internal_domain
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "grafana"
            port: 
              number: 3000
